package com.example.kmpcleanarch.data.repository

import com.example.kmpcleanarch.data.local.TaskLocalDataSource
import com.example.kmpcleanarch.data.network.NetworkMonitor
import com.example.kmpcleanarch.data.remote.api.TaskApi
import com.example.kmpcleanarch.data.sync.RequestQueue
import com.example.kmpcleanarch.domain.model.Task
import com.example.kmpcleanarch.domain.repository.TaskRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.serialization.json.Json

/**
 * Offline-first implementation of TaskRepository
 *
 * Example implementation showing how to use OfflineFirstRepository pattern.
 * Features:
 * - Local database is source of truth
 * - Optimistic updates (UI updates immediately)
 * - Automatic sync when online
 * - Queue operations when offline
 * - Cache-first data loading
 */
class OfflineFirstTaskRepository(
    private val localDataSource: TaskLocalDataSource,
    private val taskApi: TaskApi,
    networkMonitor: NetworkMonitor,
    requestQueue: RequestQueue,
    json: Json = Json { ignoreUnknownKeys = true }
) : OfflineFirstRepository<Task>(networkMonitor, requestQueue, json), TaskRepository {

    override val entityType: String = "Task"

    override suspend fun insertTask(title: String): Result<Unit> {
        val task = Task(
            id = 0, // Will be generated by database
            title = title,
            description = "",
            isCompleted = false,
            createdAt = System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis()
        )

        return createOptimistically(
            entity = task,
            entityId = "temp-${System.currentTimeMillis()}", // Temporary ID until server responds
            localCreate = {
                localDataSource.insertTask(title)
            },
            remoteCreate = {
                taskApi.createTask(task)
            }
        )
    }

    override suspend fun updateTaskCompletion(taskId: Long, isCompleted: Boolean): Result<Unit> {
        // Get current task to create updated version
        val currentTask = localDataSource.getTaskById(taskId)
            ?: return Result.failure(Exception("Task not found"))

        val updatedTask = currentTask.copy(
            isCompleted = isCompleted,
            updatedAt = System.currentTimeMillis()
        )

        return updateOptimistically(
            entity = updatedTask,
            entityId = taskId.toString(),
            localUpdate = {
                localDataSource.updateTaskCompletion(taskId, isCompleted)
            },
            remoteUpdate = {
                taskApi.updateTask(updatedTask)
            }
        )
    }

    override suspend fun deleteTask(taskId: Long): Result<Unit> {
        val task = localDataSource.getTaskById(taskId)
            ?: return Result.failure(Exception("Task not found"))

        return deleteOptimistically(
            entity = task,
            entityId = taskId.toString(),
            localDelete = {
                localDataSource.deleteTask(taskId)
            },
            remoteDelete = {
                taskApi.deleteTask(taskId)
            }
        )
    }

    override fun getAllTasks(): Flow<List<Task>> {
        // Cache-first: Return local data immediately, refresh from remote in background
        return localDataSource.getAllTasks()

        // Note: For full cache-first with background refresh, you could use:
        // return fetchWithCacheFirst(
        //     cacheLoad = { localDataSource.getAllTasks() },
        //     remoteLoad = { taskApi.getAllTasks() },
        //     cacheSave = { tasks ->
        //         tasks.forEach { localDataSource.insertTask(it.title) }
        //         Result.success(Unit)
        //     }
        // )
    }

    override suspend fun getTaskById(id: Long): Task? {
        // For single items, try local first
        val local = localDataSource.getTaskById(id)

        // Try to refresh from remote if online
        if (networkMonitor.isCurrentlyConnected()) {
            try {
                val remoteResult = taskApi.getTask(id)
                if (remoteResult.isSuccess) {
                    return remoteResult.getOrNull()
                }
            } catch (e: Exception) {
                // Ignore, use local
            }
        }

        return local
    }
}
